-- Administrative governance: multiple administrators, role separation,
-- deactivation, and audited privacy-safe verification oversight.

ALTER TABLE admin_users
    ADD COLUMN role ENUM('SUPER_ADMIN','ADMIN') NOT NULL DEFAULT 'ADMIN' AFTER username,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE AFTER role,
    ADD COLUMN created_by_admin_id INT NULL AFTER password_changed_at,
    ADD COLUMN deactivated_at DATETIME NULL AFTER created_by_admin_id,
    ADD INDEX idx_admin_active_role (active, role),
    ADD CONSTRAINT fk_admin_creator FOREIGN KEY (created_by_admin_id) REFERENCES admin_users(id);

UPDATE admin_users SET role='SUPER_ADMIN' WHERE username='admin';

ALTER TABLE audit_log MODIFY COLUMN event_type ENUM(
    'ORG_APPLICATION_SUBMITTED','ORG_APPROVED','ORG_REJECTED','ORG_SUSPENDED','ORG_REINSTATED',
    'ORG_LOGIN','ORG_LOGIN_FAILED','VERIFICATION_REQUESTED','POLICY_DECISION',
    'CONSENT_SENT','CONSENT_APPROVED','CONSENT_REJECTED','CONSENT_EXPIRED',
    'RESULT_GENERATED','RESULT_SIGNED','RATE_LIMIT_TRIGGERED','INFERENCE_RISK_FLAGGED',
    'PIN_RESET_REQUESTED','PIN_RESET_COMPLETED','ACCOUNT_ACTIVATED',
    'CATEGORY_CREATED','CATEGORY_UPDATED','CATEGORY_PERMISSIONS_UPDATED',
    'ADMIN_CREATED','ADMIN_ACTIVATED','ADMIN_DEACTIVATED','ADMIN_PASSWORD_RESET',
    'ADMIN_VERIFICATION_HISTORY_VIEWED'
) NOT NULL;
