-- Phase 9 privacy-safe repeated age-probing controls and security oversight.
ALTER TABLE request_history
    ADD COLUMN decision ENUM('ALLOWED','BLOCKED') NOT NULL DEFAULT 'ALLOWED' AFTER result,
    ADD COLUMN attempt_number SMALLINT UNSIGNED NOT NULL DEFAULT 1 AFTER decision,
    ADD COLUMN reason_code VARCHAR(50) NULL AFTER attempt_number;
ALTER TABLE request_history
    DROP COLUMN result,
    ADD INDEX idx_history_security (decision,timestamp,organisation_id),
    ADD INDEX idx_history_counter (organisation_id,subject_reference,claim_family,timestamp,decision);
CREATE TABLE inference_guards (
    organisation_id INT NOT NULL,
    subject_reference VARCHAR(20) NOT NULL,
    claim_family VARCHAR(20) NOT NULL,
    last_activity_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (organisation_id,subject_reference,claim_family),
    FOREIGN KEY (organisation_id) REFERENCES organisations(id) ON DELETE CASCADE
) ENGINE=InnoDB;
ALTER TABLE verification_submissions
    ADD COLUMN denial_code VARCHAR(50) NULL AFTER verification_id,
    ADD COLUMN denial_message VARCHAR(255) NULL AFTER denial_code;
ALTER TABLE audit_log MODIFY COLUMN event_type ENUM(
    'ORG_APPLICATION_SUBMITTED','ORG_APPROVED','ORG_REJECTED','ORG_SUSPENDED','ORG_REINSTATED',
    'ORG_LOGIN','ORG_LOGIN_FAILED','VERIFICATION_REQUESTED','POLICY_DECISION',
    'CONSENT_SENT','CONSENT_VIEWED','CONSENT_APPROVAL_STARTED','CONSENT_CODE_SENT',
    'CONSENT_APPROVED','CONSENT_REJECTED','CONSENT_EXPIRED','DISCLOSURE_CREATED','DISCLOSURE_VIEWED',
    'RESULT_GENERATED','RESULT_SIGNED','RATE_LIMIT_TRIGGERED','INFERENCE_RISK_FLAGGED',
    'PIN_RESET_REQUESTED','PIN_RESET_COMPLETED','ACCOUNT_ACTIVATED',
    'CATEGORY_CREATED','CATEGORY_UPDATED','CATEGORY_PERMISSIONS_UPDATED',
    'ADMIN_CREATED','ADMIN_ACTIVATED','ADMIN_DEACTIVATED','ADMIN_PASSWORD_RESET',
    'ADMIN_ROLE_CHANGED','ADMIN_VERIFICATION_HISTORY_VIEWED','ADMIN_SECURITY_VIEWED',
    'SIGNING_KEY_CREATED','SIGNING_KEY_ACTIVATED','SIGNING_KEY_RETIRED','SIGNING_KEY_REVOKED',
    'RESULT_AUTHENTICITY_CHECKED','IDENTITY_PHOTO_VIEWED'
) NOT NULL;
