-- Phase 10 operational service availability and recovery controls.
CREATE TABLE service_status (
    service_code ENUM('NATIONAL_ID','DRIVING_LICENCE','SMS') PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    status ENUM('AVAILABLE','UNAVAILABLE') NOT NULL DEFAULT 'AVAILABLE',
    status_message VARCHAR(255) NULL,
    changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed_by_admin_id INT NULL,
    FOREIGN KEY (changed_by_admin_id) REFERENCES admin_users(id) ON DELETE SET NULL,
    INDEX idx_service_status (status)
) ENGINE=InnoDB;
INSERT INTO service_status (service_code,display_name) VALUES
    ('NATIONAL_ID','National identity service'),
    ('DRIVING_LICENCE','Driving licence service'),
    ('SMS','SMS delivery service');
ALTER TABLE audit_log MODIFY COLUMN event_type ENUM(
    'ORG_APPLICATION_SUBMITTED','ORG_APPROVED','ORG_REJECTED','ORG_SUSPENDED','ORG_REINSTATED',
    'ORG_LOGIN','ORG_LOGIN_FAILED','VERIFICATION_REQUESTED','POLICY_DECISION',
    'CONSENT_SENT','CONSENT_VIEWED','CONSENT_APPROVAL_STARTED','CONSENT_CODE_SENT',
    'CONSENT_APPROVED','CONSENT_REJECTED','CONSENT_EXPIRED','DISCLOSURE_CREATED','DISCLOSURE_VIEWED',
    'RESULT_GENERATED','RESULT_SIGNED','RATE_LIMIT_TRIGGERED','INFERENCE_RISK_FLAGGED',
    'PIN_RESET_REQUESTED','PIN_RESET_COMPLETED','ACCOUNT_ACTIVATED',
    'CATEGORY_CREATED','CATEGORY_UPDATED','CATEGORY_PERMISSIONS_UPDATED',
    'ADMIN_CREATED','ADMIN_ACTIVATED','ADMIN_DEACTIVATED','ADMIN_PASSWORD_RESET',
    'ADMIN_ROLE_CHANGED','ADMIN_VERIFICATION_HISTORY_VIEWED','ADMIN_SECURITY_VIEWED',
    'SERVICE_STATUS_CHANGED','SERVICE_UNAVAILABLE',
    'SIGNING_KEY_CREATED','SIGNING_KEY_ACTIVATED','SIGNING_KEY_RETIRED','SIGNING_KEY_REVOKED',
    'RESULT_AUTHENTICITY_CHECKED','IDENTITY_PHOTO_VIEWED'
) NOT NULL;
