ALTER TABLE organisations MODIFY COLUMN status
    ENUM('PENDING','NEEDS_INFORMATION','APPROVED','REJECTED','SUSPENDED') NOT NULL DEFAULT 'PENDING';

ALTER TABLE organisation_evidence_submissions
    ADD COLUMN review_status ENUM('PENDING','ACCEPTED','REJECTED') NOT NULL DEFAULT 'PENDING' AFTER expires_on,
    ADD COLUMN review_notes VARCHAR(500) NULL AFTER review_status,
    ADD COLUMN reviewed_by_admin_id INT NULL AFTER review_notes,
    ADD COLUMN reviewed_at DATETIME NULL AFTER reviewed_by_admin_id,
    ADD CONSTRAINT fk_evidence_review_admin FOREIGN KEY (reviewed_by_admin_id) REFERENCES admin_users(id);

CREATE TABLE organisation_application_reviews (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    organisation_id INT NOT NULL,
    administrator_id INT NULL,
    action ENUM('APPLICATION_SUBMITTED','EVIDENCE_ACCEPTED','EVIDENCE_REJECTED','MORE_INFORMATION_REQUESTED','APPROVED','REJECTED','EVIDENCE_RESUBMITTED') NOT NULL,
    notes VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (organisation_id) REFERENCES organisations(id) ON DELETE CASCADE,
    FOREIGN KEY (administrator_id) REFERENCES admin_users(id),
    INDEX idx_application_review_org_time (organisation_id,created_at)
) ENGINE=InnoDB;

INSERT INTO organisation_application_reviews (organisation_id,action,created_at)
SELECT id,'APPLICATION_SUBMITTED',created_at FROM organisations;

ALTER TABLE audit_log MODIFY COLUMN event_type ENUM(
    'ORG_APPLICATION_SUBMITTED','ORG_APPROVED','ORG_REJECTED','ORG_SUSPENDED','ORG_REINSTATED','ORG_MORE_INFORMATION_REQUESTED',
    'ORG_LOGIN','ORG_LOGIN_FAILED','VERIFICATION_REQUESTED','POLICY_DECISION',
    'CONSENT_SENT','CONSENT_VIEWED','CONSENT_APPROVAL_STARTED','CONSENT_CODE_SENT',
    'CONSENT_APPROVED','CONSENT_REJECTED','CONSENT_EXPIRED','DISCLOSURE_CREATED','DISCLOSURE_VIEWED',
    'RESULT_GENERATED','RESULT_SIGNED','RATE_LIMIT_TRIGGERED','INFERENCE_RISK_FLAGGED',
    'PIN_RESET_REQUESTED','PIN_RESET_COMPLETED','ACCOUNT_ACTIVATED',
    'CATEGORY_CREATED','CATEGORY_UPDATED','CATEGORY_PERMISSIONS_UPDATED',
    'ADMIN_CREATED','ADMIN_ACTIVATED','ADMIN_DEACTIVATED','ADMIN_PASSWORD_RESET',
    'ADMIN_ROLE_CHANGED','ADMIN_VERIFICATION_HISTORY_VIEWED','ADMIN_SECURITY_VIEWED',
    'SERVICE_STATUS_CHANGED','SERVICE_UNAVAILABLE',
    'SIGNING_KEY_CREATED','SIGNING_KEY_ACTIVATED','SIGNING_KEY_RETIRED','SIGNING_KEY_REVOKED',
    'RESULT_AUTHENTICITY_CHECKED','IDENTITY_PHOTO_VIEWED'
) NOT NULL;
